# Copyright (C) 2026 Chris Burdess <dog@gnu.org>

[package]
name = "smtp-ldap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "smtp-ldap"
path = "main.rs"

[dependencies]
hopf-core = { workspace = true }
hopf-smtp = { workspace = true }
hopf-ldap = { workspace = true }
hopf-tls = { workspace = true }
