# Copyright (C) 2026 Chris Burdess <dog@gnu.org>

[package]
name = "imap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "imap"
path = "main.rs"

[dependencies]
hopf-core = { workspace = true }
hopf-imap = { workspace = true }
hopf-mailbox = { workspace = true }
hopf-auth = { workspace = true }
