# Copyright (C) 2026 Chris Burdess <dog@gnu.org>

[package]
name = "http-get"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "http-get"
path = "main.rs"

[dependencies]
hopf-core = { workspace = true }
hopf-http = { workspace = true, features = ["h3"] }
hopf-dns = { workspace = true }
hopf-quic = { workspace = true }
hopf-tls = { workspace = true }
