[package]
name = "websocket-echo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "websocket-echo"
path = "main.rs"

[dependencies]
hopf-core = { workspace = true }
hopf-http = { workspace = true }
hopf-websocket = { workspace = true }
