[package]
name = "hopf-smtp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "SMTP / SMTPS server and client for Hopf (Gumdrop smtp port)"
readme = "README.md"
keywords = ["smtp", "smtps", "email", "networking"]
categories = ["network-programming", "email"]

[features]
default = []
integration = []

[dependencies]
hopf-core = { workspace = true }
hopf-auth = { workspace = true }
hopf-tls = { workspace = true }
hopf-otel = { workspace = true }
hopf-dns = { workspace = true }
rmimeparser = { workspace = true }
rustls = { workspace = true }
base64 = "0.22"

[dev-dependencies]
tempfile = { workspace = true }
rcgen = { workspace = true }
