# Copyright (C) 2026 Chris Burdess <dog@gnu.org>

[package]
name = "amqp-pub"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "amqp-pub"
path = "main.rs"

[dependencies]
hopf-core = { workspace = true }
hopf-amqp = { workspace = true }
