# Copyright (C) 2026 Chris Burdess <dog@gnu.org>

[package]
name = "mqtt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "mqtt"
path = "main.rs"

[dependencies]
hopf-core = { workspace = true }
hopf-mqtt = { workspace = true }
hopf-auth = { workspace = true }
